spring:
 datasource:
   url: ${PMDB_URL}
   username: ${PMDB_USER}
   password: ${PMDB_PASS}
 jpa:
   database-platform: org.hibernate.dialect.PostgreSQLDialect
   hibernate:
     ddl-auto: create
   show-sql: true